services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
       KAFKA_KRAFT_MODE: 'true'

       CLUSTER_ID:  'xys_logs_xys_logs_xys'
       KAFKA_NODE_ID: 1 # just 1 node

       KAFKA_PROCESS_ROLES: broker, controller
       KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # just 1 copy 

       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092, CONTROLLER://0.0.0.0:9093
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
       KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

    volumes:
      - kafka-kraft:/var/lib/kafka/data


  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    
    volumes:
      - mongo-data:/data/db

  node:
    build: .
    container_name: logging-ms
    ports:
      - "5000:5000"

    depends_on:
    - mongodb
    - kafka


volumes:
  kafka-kraft:   
  mongo-data:
