apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: logging-ms-cluster  
  region: eu-north-1  
managedNodeGroups:
  - name: workers
    instanceType: t3.small  
    minSize: 1
    maxSize: 2
    desiredCapacity: 2